### ISSUE TITLE
titan db

### ISSUE THREAD

**Issue by iatila** [tkaratug/TitanDB#2]
Notice: Undefined index: db_name in C:\xampp\htdocs\tt\system\plugins\Database.php on line 87

Notice: Undefined index: db_user in C:\xampp\htdocs\tt\system\plugins\Database.php on line 97

Notice: Undefined index: db_pass in C:\xampp\htdocs\tt\system\plugins\Database.php on line 97

Notice: Undefined index: db_name in C:\xampp\htdocs\tt\system\plugins\Database.php on line 87

Notice: Undefined index: db_user in C:\xampp\htdocs\tt\system\plugins\Database.php on line 97

Notice: Undefined index: db_pass in C:\xampp\htdocs\tt\system\plugins\Database.php on line 97

ENVIRONMENT geliştirici kısmında oldugunda  bu hatayı alıyorum

**Comment by tkaratug** [comment]
/app/config dizini içerisinde "development" adında bir dizin oluşturun. config'deki db dosyasını buraya kopyalayın ve database erişim bilgilerinizi development ortamına göre buraya girin.
